web/protected/models/Usuarios.php
<?php

/**
 * This is the model class for table "usuarios".
 *
 * The followings are the available columns in table 'usuarios':
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $nombre
 * @property string $apellido
 * @property string $email
 * @property string $telefono
 * @property string $estado
 *
 * The followings are the available model relations:
 * @property Usuariopermisos[] $usuariopermisoses
 */
class Usuarios extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'usuarios';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, password, nombre, apellido, estado', 'required'),
			array('username, password', 'length', 'max'=>50),
			array('nombre, apellido, email, telefono', 'length', 'max'=>100),
			array('estado', 'length', 'max'=>1),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, username, password, nombre, apellido, email, telefono, estado', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'permisos' => array(self::HAS_MANY, 'Usuariopermisos', 'idusuario'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Username',
			'password' => 'Password',
			'nombre' => 'Nombre',
			'apellido' => 'Apellido',
			'email' => 'Email',
			'telefono' => 'Telefono',
			'estado' => 'Estado',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('nombre',$this->nombre,true);
		$criteria->compare('apellido',$this->apellido,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('telefono',$this->telefono,true);
		$criteria->compare('estado',$this->estado,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Checks if the given password is correct.
	 * @param string the password to be validated
	 * @return boolean whether the password is valid
	 */
	public function validatePassword($password)
	{
		return $password === $this->password;
	}


	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Usuarios the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

web/protected/controllers/UsuariosController.php
<?php


class UsuariosController extends Controller
{
	public $layout='main_intranet';

	public function filters(){
		return array('accessControl', // perform access control for CRUD operations
		);
	}

	public function accessRules(){
		return array(
			array('deny', //no entra a ninguna accion ningun usuario que no este logueado               
                'users'=>array('?'),
            ),
            array('allow', // acceden todos los usuarios autenticados a todas las acciones
				//'actions'=>Yii::app()->user->getRules(),
				'users'=>array('@'),
            )	
        );
	}
	
	public function actionIndex()
	{
		$usuarios = Usuarios::model()->findAll(array('condition'=>'estado!=:estado','params'=>array('estado'=>'E')));
		$permisos = Permisos::model()->findAll();
		$this->render('index', array('usuarios'=>$usuarios, 'permisos'=>$permisos));
	}

	public function actionActualizarEstado()
	{
		if(!empty($_POST['idUsuario'])){
			$usuario = Usuarios::model()->findByPk($_POST['idUsuario']);
			$usuario->estado = $_POST['estado'];
			if($usuario->update()){
				echo json_encode(array(
					"status"=>"ok",
					"msg"=>"Estado actualizado."
					));
			}else{
				echo json_encode(array(
					"status"=>"error",
					"msg"=>"No se pudo actualizar el estado."
					));
			}
		}
	}

	public function actionAgregar()
	{
		$model = new Usuarios;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Usuarios']))
		{//echo '<pre>';print_r($_POST);die;
			$_POST['Usuarios']['estado'] = isset($_POST['Usuarios']['estado']) && $_POST['Usuarios']['estado'] == 'on' ? '1':'0';
			$_POST['Usuarios']['password'] = isset($_POST['Usuarios']['confirmarEmail']) && $_POST['Usuarios']['confirmarEmail'] == 'on' ? Utils::generarToken(6):Yii::app()->params['passwordDefault'];
			$model->attributes=$_POST['Usuarios'];
			if($model->save()){
				if(!empty($_POST['Usuarios']['permisos'])){
					foreach($_POST['Usuarios']['permisos'] as $permiso){
						$usuariopermisos=new Usuariopermisos;
						$usuariopermisos->idusuario=$model->id;
						$usuariopermisos->idpermiso=$permiso;
						$usuariopermisos->save();
					}
				}
				$this->redirect(array('index'));
			}
		}

		$this->render('form',array(
			'model'=>$model,
		));
	}

	public function actionEditar($id)
	{
		$model = Usuarios::model()->findByPk($id);
		if($model->estado == 'E')
			$this->redirect('../../usuarios');
		
		if(isset($_POST['Usuarios']))
		{
			$_POST['Usuarios']['estado'] = isset($_POST['Usuarios']['estado']) && $_POST['Usuarios']['estado'] == 'on' ? '1':'0';
			$model->attributes=$_POST['Usuarios'];
			if($model->save()){
				Usuariopermisos::model()->deleteAll("idusuario=$id");
				if(!empty($_POST['Usuarios']['permisos'])){
					foreach($_POST['Usuarios']['permisos'] as $permiso){
						$usuariopermisos=new Usuariopermisos;
						$usuariopermisos->idusuario=$id;
						$usuariopermisos->idpermiso=$permiso;
						$usuariopermisos->save();
					}
				}
				$this->redirect('../../usuarios');
			}
		}

		// Se recuperan los permisos del usuario.
		$permisosUsuario = array();
		if(!empty($model->permisos)){
			foreach($model->permisos as $permiso){
				array_push($permisosUsuario, $permiso->idpermiso);
			}
		}
		// Se ordenan los permisos de forma ascendente.
		sort($permisosUsuario);

		$this->render('form',array(
			'model'=>$model,
			'permisosUsuario'=>$permisosUsuario,
		));
	}

	public function actionEliminar($id)
	{ 
		// Usuarios::model()->findByPk($id)->delete();
		$model = Usuarios::model()->findByPk($id);
		$model->estado = 'E';
		$model->update();
		$this->redirect('../../usuarios');	
	}

	public function actionResetpassword()
	{
		if(isset($_POST))
		{	
			$usuario = Usuarios::model()->findByPk(Yii::app()->user->id);
			$usuario->password = $_POST['password_1'];
			if($usuario->update()){
				echo json_encode(array(
					"status"=>"ok",
					"msg"=>"Password actualizado."
					));
			}else{
				echo json_encode(array(
					"status"=>"error",
					"msg"=>"No se pudo actualizar el Password."
					));
			}
		}
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

web/protected/views/usuarios/form.php
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Editar</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/inicio">Inicio</a></li>
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/usuarios">Usuarios</a></li>
              <li class="breadcrumb-item active">Editar</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Usuario</h3>
                        </div><!-- /.card-header -->
                        <?php 
                            $form=$this->beginWidget('CActiveForm', array(
                                //'action'=>Yii::app()->request->baseUrl.'/'.Yii::app()->controller->id.'/login',
                                //'method'=>'post',
                                'id'=>'usuario-form',
                                'enableAjaxValidation'=>false,
                                //'htmlOptions'=>array('enctype'=>'multipart/form-data'),
                            )); 
                        ?>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success float-right">
                                                <?php //echo $form->checkBox($model,'estado',array('class'=>'custom-control-input', 'id'=>'chk-'.$model->id,'checked'=>'checked')); ?>
                                                <input type="checkbox" class="custom-control-input" name="Usuarios[estado]" id="chk-<?=$model->id?>" <?=$model->estado=='1'?'checked':'';?>>
                                                <label class="custom-control-label" for="chk-<?=$model->id?>">Activo</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'nombre'); ?>
                                            <?php echo $form->textField($model,'nombre',array('class'=>'form-control')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'apellido'); ?>
                                            <?php echo $form->textField($model,'apellido',array('class'=>'form-control')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'email'); ?>
                                            <?php echo $form->textField($model,'email',array('class'=>'form-control')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'telefono'); ?>
                                            <?php echo $form->textField($model,'telefono',array('class'=>'form-control')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'username'); ?>
                                            <?php echo $form->textField($model,'username',array('class'=>'form-control', 'placeholder'=>'','required'=>true)); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <?php if(Yii::app()->controller->action->id=='agregar'){?>
                                        <div class="form-group form-group-check">
                                            <div class="custom-control custom-checkbox">
                                                <input type="checkbox" name="Usuarios[confirmarEmail]" class="custom-control-input" id="confirmacion">
                                                <label class="custom-control-label" for="confirmacion">Enviar confirmación al email</label>
                                            </div>
                                        </div>
                                        <?php } ?>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="Usuarios_permisos" class="required">Permisos</label>
                                            <?php $listaPermisos = CHtml::listData(Permisos::model()->findAll(array('condition'=>'estado=:estado','params'=>array('estado'=>'1'),'order'=>'id')), 'id', 'nombre'); ?>
                                            <?php echo $form->dropDownList($model,'permisos',$listaPermisos,array('class'=>'form-control select2', 'multiple'=>'multiple')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <?php echo CHtml::submitButton('Guardar',array('class'=>'btn btn-primary btn-guardar')); ?>
                                <?php echo CHtml::link('Cancelar', Yii::app()->request->baseUrl.'/usuarios' , array('class'=>'btn btn-default')); ?>
                            </div>
                        <?php $this->endWidget(); ?>
                    </div><!-- /.card -->
                </div>
            </div> <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section><!-- /.content -->
</div>
<script> 
    var permisosUsuario = JSON.parse('<?=!empty($permisosUsuario)?json_encode($permisosUsuario):json_encode(array())?>');
    var action = '<?=Yii::app()->controller->action->id?>';
</script>

web/protected/views/usuarios/index.php
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><?=ucwords($this->id)?></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/inicio">Inicio</a></li>
              <li class="breadcrumb-item active"><?=ucwords($this->id)?></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-12">
            <div class="card">
              <div class="card-header">
                <?php echo CHtml::link('Agregar', Yii::app()->request->baseUrl.'/usuarios/agregar' , array('class'=>'btn btn-primary float-right')); ?>
              </div><!-- /.card-header -->
              <div class="card-body">
                <table id="admin-usuarios" class="table table-bordered table-striped" style="width:100%">
                  <thead>
                    <tr>
                      <th>Activo</th>
                      <th>Usuario</th>
                      <th>Nombre</th>
                      <th>Apellido</th>
                      <th>Acciones</th>
                      <th>Usuarios</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php if(!empty($usuarios)){ ?>
                      <?php foreach($usuarios as $usuario){ ?>
                        <tr>
                            <td>
                              <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                <input type="checkbox" class="custom-control-input chk-estado" id="chk-desktop-<?=$usuario->id?>" <?=$usuario->estado=='1'?'checked':'';?>>
                                <label class="custom-control-label" for="chk-desktop-<?=$usuario->id?>"></label>
                              </div>
                            </td>
                            <td><?=$usuario->username?></td>
                            <td><?=$usuario->nombre?></td>
                            <td><?=$usuario->apellido?></td>
                            <td>
                              <a href="<?=Yii::app()->request->baseUrl.'/usuarios/editar/'.$usuario->id?>" class="btn btn-default"><i class="fas fa-edit"></i></a>
                              <a href="<?=Yii::app()->request->baseUrl.'/usuarios/eliminar/'.$usuario->id?>" class="btn btn-default btn-eliminar" data-toggle="modal" data-target="#modal-eliminar-usuario"><i class="fas fa-trash-alt"></i></a>
                            </td>
                            <td>
                              <div class="box-mobile">
                                <div class="box-body">
                                  <div class="box-item"><?=$usuario->estado?></div>
                                  <div class="box-item"><?=$usuario->username?></div>
                                </div>
                                <div class="box-body">
                                  <div class="box-item"><?=$usuario->nombre?> <?=$usuario->apellido?></div>
                                  <div class="box-item">Acciones</div>
                                </div>
                              </div>
                            </td>
                        </tr>
                        <?php }// foreach usuarios ?>
                      <?php }// if usuarios ?>
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
		  
          </div>
          
        </div>
        <!-- /.row -->
        
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php require "modal_eliminar.php"; ?>

web/protected/views/usuarios/modal_eliminar.php
<div class="modal fade" id="modal-eliminar-usuario">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Atención</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>¿Estás seguro de eliminar al usuario?</p>
        </div>
        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <a href="#" class="btn btn-primary" id="btn-continuar">Continuar</a>
        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

web/protected/views/usuarios/modal_reset_password.php
<div class="modal fade" id="modal-reset-password">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Cambiar contraseña</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="form-reset-password">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="password-1" class="required">Nueva contraseña *</label>
                                <input type="text" class="form-control" id="password-1" required/>
                                <div class="invalid-feedback">
                                    Complete el campo.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="password-2" class="required">Confirmar contraseña *</label>
                                <input type="text" class="form-control" id="password-2" required/>
                                <div class="invalid-feedback">
                                    Complete el campo.
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <a href="#" class="btn btn-primary" id="btn-reset-password">Continuar</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->