web/protected/models/Turnos.php
<?php

/**
 * This is the model class for table "turnos".
 *
 * The followings are the available columns in table 'turnos':
 * @property integer $id
 * @property string $fecha
 * @property integer $cupo
 * @property string $activodesde
 * @property string $activohasta
 * @property integer $idhorario
 * @property string $estado
 *
 * The followings are the available model relations:
 * @property Reservas[] $reservases
 * @property Horarios $idhorario0
 */
class Turnos extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'turnos';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('fecha, cupo, activodesde, activohasta, idhorario, estado', 'required'),
			array('cupo, idhorario', 'numerical', 'integerOnly'=>true),
			array('estado', 'length', 'max'=>1),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, fecha, cupo, activodesde, activohasta, idhorario, estado', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'reservas' => array(self::HAS_MANY, 'Reservas', 'idturno'),
			'horario' => array(self::BELONGS_TO, 'Horarios', 'idhorario'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'fecha' => 'Fecha',
			'cupo' => 'Cupo',
			'activodesde' => 'Activo desde',
			'activohasta' => 'Activo hasta',
			'idhorario' => 'Horario',
			'estado' => 'Estado',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('fecha',$this->fecha,true);
		$criteria->compare('cupo',$this->cupo);
		$criteria->compare('activodesde',$this->activodesde,true);
		$criteria->compare('activohasta',$this->activohasta,true);
		$criteria->compare('idhorario',$this->idhorario);
		$criteria->compare('estado',$this->estado,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Turnos the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

web/protected/controllers/TurnosController.php
<?php

class TurnosController extends Controller
{
	public $layout='main_intranet';

	public function filters(){
		return array('accessControl', // perform access control for CRUD operations
		);
	}

	public function accessRules(){
		return array(
			array('deny', //no entra a ninguna accion ningun usuario que no este logueado               
                'users'=>array('?'),
            ),
            array('allow', // acceden todos los usuarios autenticados a todas las acciones
				//'actions'=>Yii::app()->user->getRules(),
				'users'=>array('@'),
            )	
        );
	}

	public function actionIndex()
	{
		$turnos = Turnos::model()->findAll(array('condition'=>'estado!=:estado','params'=>array('estado'=>'E')));
		$this->render('index', array('turnos'=>$turnos));
	}

	public function actionActualizarEstado()
	{
		if(!empty($_POST['idTurno'])){
			$turno = Turnos::model()->findByPk($_POST['idTurno']);
			$turno->estado = $_POST['estado'];
			if($turno->update()){
				echo json_encode(array(
					"status"=>"ok",
					"msg"=>"Estado actualizado."
					));
			}else{
				echo json_encode(array(
					"status"=>"error",
					"msg"=>"No se pudo actualizar el estado."
					));
			}
		}
	}

	public function actionEditar($id)
	{
		$model = Turnos::model()->findByPk($id);
		if($model->estado == 'E')
			$this->redirect('../../turnos');
		
		if(isset($_POST['Turnos']))
		{
			$_POST['Turnos']['estado'] = isset($_POST['Turnos']['estado']) && $_POST['Turnos']['estado'] == 'on' ? '1':'0';
			//$_POST['Turnos']['fecha'] = Utils::fechaBD($_POST['Turnos']['fecha']);
			$_POST['Turnos']['activodesde'] = Utils::fechaBD($_POST['Turnos']['activodesde']);
			$_POST['Turnos']['activohasta'] = Utils::fechaBD($_POST['Turnos']['activohasta']);
			$model->attributes=$_POST['Turnos'];
			if($model->save()){
				$this->redirect('../../turnos');
			}
		}

		// Modifico el formato de las fechas para el calendario.
		$model->fecha = Utils::fechaWeb($model->fecha);
		$model->activodesde = Utils::fechaWeb($model->activodesde);
		$model->activohasta = Utils::fechaWeb($model->activohasta);
		
		$this->render('form',array(
			'model'=>$model,
		));
	}

	public function actionAgregar()
	{
		if(isset($_POST['Turnos']))
		{ 
			$_POST['Turnos']['estado'] = isset($_POST['Turnos']['estado']) && $_POST['Turnos']['estado'] == 'on' ? '1':'0';
			$fechas = explode(' - ',$_POST['Turnos']['fecha']);
			$desde = Utils::fechaBD($fechas[0]);
			$hasta = Utils::fechaBD($fechas[1]);
			$activoDesde = Utils::fechaBD($_POST['Turnos']['activodesde']);
			$activohasta = Utils::fechaBD($_POST['Turnos']['activohasta']);
			if($_POST['Turnos']['horario'] == 'all'){
				$horarios = Horarios::model()->findAll(array('condition'=>'estado=:estado','params'=>array('estado'=>'1')));
			}else{
				$horarios = Horarios::model()->findAll(array('condition'=>'estado=:estado AND id=:id','params'=>array('estado'=>'1','id'=>$_POST['Turnos']['horario'] )));
			}
			
			$idHorarios = array();
			foreach($horarios as $horario){
				$idHorarios[$horario->dia][] = $horario->id;
			}

			$inicio = new DateTime($desde);
			$fin   = new DateTime($hasta);
			$inicioActivo = new DateTime($activoDesde);
			$finActivo   = new DateTime($activohasta);

			for($fecha = $inicio; $fecha <= $fin; $fecha->modify('+1 day')){
				$dia = Utils::diaWeb($fecha->format("D"));
				if(array_key_exists($dia, $idHorarios)){
					foreach($idHorarios[$dia] as $id){
						$model = new Turnos;
						$model->fecha = $fecha->format("Y-m-d");
						$model->cupo = $_POST['Turnos']['cupo'];
						$model->activodesde = $inicioActivo->format("Y-m-d");
						$model->activohasta = $finActivo->format("Y-m-d");
						$model->idhorario = $id;
						$model->estado = $_POST['Turnos']['estado'];
						$model->save();
					}
				}
			}
			$this->redirect(array('index'));
			
		}

		$this->render('form_publicar');
	}

	public function actionEliminar($id)
	{ 
		// Turnos::model()->findByPk($id)->delete();
		$model = Turnos::model()->findByPk($id);
		$model->estado = 'E';
		$model->update();
		// Elimino las reservas del turno
		$reservas = Reservas::model()->findAll(array('condition'=>'idturno=:idturno AND estado!=:estado','params'=>array('idturno'=>$model->id, 'estado'=>'E')));
		foreach($reservas as $reserva){
			$reserva->estado = 'E';
			$reserva->update();
		}
		$this->redirect('../../turnos');	
	}
	
}

web/protected/views/turnos/form.php
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><?=Yii::app()->controller->action->id?></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/inicio">Inicio</a></li>
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/turnos">Turnos</a></li>
              <li class="breadcrumb-item active">Editar</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Turno</h3>
                        </div><!-- /.card-header -->
                        <?php 
                            $form=$this->beginWidget('CActiveForm', array(
                                //'action'=>Yii::app()->request->baseUrl.'/'.Yii::app()->controller->id.'/login',
                                //'method'=>'post',
                                'id'=>'horario-form',
                                'enableAjaxValidation'=>false,
                                //'htmlOptions'=>array('enctype'=>'multipart/form-data'),
                            )); 
                        ?>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success float-right">
                                                <?php //echo $form->checkBox($model,'estado',array('class'=>'custom-control-input', 'id'=>'chk-'.$model->id,'checked'=>'checked')); ?>
                                                <input type="checkbox" class="custom-control-input" name="Turnos[estado]" id="chk-<?=$model->id?>" <?=$model->estado=='1'?'checked':'';?>>
                                                <label class="custom-control-label" for="chk-<?=$model->id?>">Activo</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'fecha'); ?>
                                            <?php echo $form->textField($model,'fecha',array('class'=>'form-control single-calendar','disabled'=>'disabled')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'cupo'); ?>
                                            <?php echo $form->numberField($model,'cupo',array('class'=>'form-control','min'=>'0')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'activodesde'); ?>
                                            <?php echo $form->textField($model,'activodesde',array('class'=>'form-control single-calendar')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <?php echo $form->labelEx($model,'activohasta'); ?>
                                            <?php echo $form->textField($model,'activohasta',array('class'=>'form-control single-calendar')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="Turnos_permisos" class="required">Horario</label>
                                            <?php $listaPermisos = CHtml::listData(Horarios::model()->findAll(array('condition'=>'estado=:estado','params'=>array('estado'=>'1'),'order'=>'dia ASC, horainicio ASC')), 'id', function($horario){ return $horario->dia." de ".$horario->horainicio." a ".$horario->horafin; }); ?>
                                            <?php echo $form->dropDownList($model,'idhorario',$listaPermisos,array('class'=>'form-control select2','disabled'=>'disabled')); ?>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <?php echo CHtml::submitButton('Guardar',array('class'=>'btn btn-primary btn-guardar')); ?>
                                <?php echo CHtml::link('Cancelar', Yii::app()->request->baseUrl.'/turnos' , array('class'=>'btn btn-default')); ?>
                            </div>
                        <?php $this->endWidget(); ?>
                    </div><!-- /.card -->
                </div>
            </div> <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section><!-- /.content -->
</div>
<script>
    var action = '<?=Yii::app()->controller->action->id?>';
</script>

web/protected/views/turnos/form_publicar.php
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><?=Yii::app()->controller->action->id?></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/inicio">Inicio</a></li>
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/turnos">Turnos</a></li>
              <li class="breadcrumb-item active">Editar</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Turno</h3>
                        </div><!-- /.card-header -->
                        <form action="<?=Yii::app()->request->baseUrl.'/'.Yii::app()->controller->id.'/agregar'?>" method="post">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success float-right">
                                                <input type="checkbox" class="custom-control-input" name="Turnos[estado]" id="chk-estado">
                                                <label class="custom-control-label" for="chk-estado">Activo</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <label for="Turnos_fecha" class="required">Fecha *</label>
                                            <input type="text" name="Turnos[fecha]" class="form-control calendar" id="Turnos_fecha" autocomplete="off">
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <label for="Turnos_cupo" class="required">Cupo *</label>
                                            <input type="number" name="Turnos[cupo]" class="form-control" id="Turnos_cupo" min="0" value="0">
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <label for="Turnos_desde" class="required">Activo desde *</label>
                                            <input type="text" name="Turnos[activodesde]" class="form-control single-calendar" id="Turnos_desde" autocomplete="off">
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <label for="Turnos_hasta" class="required">Activo hasta *</label>
                                            <input type="text" name="Turnos[activohasta]" class="form-control single-calendar" id="Turnos_hasta" autocomplete="off">
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="Turnos_horario" class="required">Horario *</label>
                                            <?php $listaHorarios = CHtml::listData(Horarios::model()->findAll(array('condition'=>'estado=:estado','params'=>array('estado'=>'1'),'order'=>'dia ASC, horainicio ASC')), 'id', function($horario){ return $horario->dia." de ".$horario->horainicio." a ".$horario->horafin; }); ?>
                                            <?php //echo '<pre>';print_r($listaHorarios);die;?>
                                            <select class="form-control select2" name="Turnos[horario]" id="Turnos_horario">
                                                <option value="all">Todos los horarios</option>
                                                <?php foreach($listaHorarios as $key => $horario){ ?>
                                                    <option value="<?=$key?>"><?=$horario?></option>
                                                <?php } ?>
                                            </select>
                                            <div class="invalid-feedback">
                                                Complete el campo.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <?php echo CHtml::submitButton('Guardar',array('class'=>'btn btn-primary btn-guardar')); ?>
                                <?php echo CHtml::link('Cancelar', Yii::app()->request->baseUrl.'/turnos' , array('class'=>'btn btn-default')); ?>
                            </div>
                        </form>
                    </div><!-- /.card -->
                </div>
            </div> <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section><!-- /.content -->
</div>
<script>
    var action = '<?=Yii::app()->controller->action->id?>';
</script>

web/protected/views/turnos/index.php
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><?=ucwords($this->id)?></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<?=Yii::app()->request->baseUrl?>/inicio">Inicio</a></li>
              <li class="breadcrumb-item active"><?=ucwords($this->id)?></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-12">
            <div class="card">
              <div class="card-header">
                <?php echo CHtml::link('Agregar', Yii::app()->request->baseUrl.'/turnos/agregar' , array('class'=>'btn btn-primary float-right')); ?>
              </div><!-- /.card-header -->
              <div class="card-body">
                <table id="admin-turnos" class="table table-bordered table-striped" style="width:100%">
                  <thead>
                    <tr>
                      <th>Activo</th>
                      <th>Día</th>
                      <th>Cupo</th>
                      <th>Activo desde</th>
					            <th>Activo hasta</th>
                      <th>Acciones</th>
                      <th>Turnos</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php if(!empty($turnos)){ ?>
                      	<?php foreach($turnos as $turno){
                          $order = '';
                          switch($turno->horario->dia){
                            case 'LUN': $order='1'; break;
                            case 'MAR': $order='2'; break;
                            case 'MIE': $order='3'; break;
                            case 'JUE': $order='4'; break;
                            case 'VIE': $order='5'; break;
                            case 'SAB': $order='6'; break;
                            case 'DOM': $order='7'; break;
                          }
                          ?>
                          <tr>
                            <td>
                            <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                              <input type="checkbox" class="custom-control-input chk-estado" id="chk-desktop-<?=$turno->id?>" <?=$turno->estado=='1'?'checked':'';?>>
                              <label class="custom-control-label" for="chk-desktop-<?=$turno->id?>"></label>
                            </div>
                            </td>
                            <td data-order="<?=$turno->fecha.'-'.$order.'-'.$turno->horario->horainicio?>">
                              <span><?=$turno->horario->dia?></span> <?=Utils::fechaWeb($turno->fecha)?> 
                              <p class="text-horario text-detail">de <?=$turno->horario->horainicio?> a <?=$turno->horario->horafin?></p>
                            </td>
                            <td><?=$turno->cupo?></td>
                            <td><?=Utils::fechaWeb($turno->activodesde)?></td>
                            <td><?=Utils::fechaWeb($turno->activohasta)?></td>
                            <td>
                            <a href="<?=Yii::app()->request->baseUrl.'/turnos/editar/'.$turno->id?>" class="btn btn-default"><i class="fas fa-edit"></i></a>
                            <a href="<?=Yii::app()->request->baseUrl.'/turnos/eliminar/'.$turno->id?>" class="btn btn-default btn-eliminar" data-toggle="modal" data-target="#modal-eliminar-turno"><i class="fas fa-trash-alt"></i></a>
                            </td>
                            <td>
                            <div class="box-mobile">
                              <div class="box-body">
                              <div class="box-item"><?=$turno->estado?></div>
                              <div class="box-item"><?=$turno->fecha?></div>
                              </div>
                              <div class="box-body">
                              <div class="box-item"><?=$turno->activodesde?> <?=$turno->activohasta?></div>
                              <div class="box-item">Acciones</div>
                              </div>
                            </div>
                            </td>
                        	</tr>
                        <?php }// foreach usuarios ?>
                      <?php }// if usuarios ?>
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
		  
          </div>
          
        </div>
        <!-- /.row -->
        
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php require "modal_eliminar.php"; ?>

web/protected/views/turnos/modal_eliminar.php
<div class="modal fade" id="modal-eliminar-turno">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Atención</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>¿Estás seguro de eliminar el turno?</p>
            <p class="text-gray">*Si eliminas el turno, se eliminarán las reservas asociados a él.</p>
        </div>
        <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <a href="#" class="btn btn-primary" id="btn-continuar-turno">Continuar</a>
        </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->